<?php
namespace Appointment\Controller;

use Zend\Mvc\Controller\AbstractActionController;

Class AppointmentController extends AbstractActionController{

    public function indexAction()
    {
        return parent::indexAction(); // TODO: Change the autogenerated stub
    }

    public function addAction()
    {

    }

    public function editAction()
    {

    }

    public function deleteAction()
    {

    }
}